:soundcloud:
  :username: 'username'
  :password: 'password'
  :client_id: 'client_id'
  :client_secret: 'client_secret'
  
:filesmanager:
  :dest: '/path/to/folder/'
  :max_db: '200'
  :max_per_cycle: '5'
  